--- 
name: maven
networks: 
  seleniumGrid: ~
true: 
  pull_request: 
    branches: 
      - master
  push: 
    branches: 
      - master
  services: 
    chrome: 
      container_name: Chrome-1
      depends_on: 
        - selenium-hub
      environment: 
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - NODE_MAX_INSTANCES=2
        - NODE_MAX_SESSIONS=2
      image: "selenium/node-chrome:3.141.59-zinc"
      networks: 
        - seleniumGrid
    chrome2: 
      container_name: Chrome-2
      depends_on: 
        - selenium-hub
      environment: 
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - NODE_MAX_INSTANCES=2
        - NODE_MAX_SESSIONS=2
      image: "selenium/node-chrome:3.141.59-zinc"
      networks: 
        - seleniumGrid
    selenium-hub: 
      container_name: selenium-hub
      image: "selenium/hub:3.141.59-zinc"
      networks: 
        - seleniumGrid
      ports: 
        - "4444:4444"
