name: maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ build_application ]
jobs:
  build:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start Container
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Build with Maven
        run: SELENIUM_REMOTE_URL=http://localhost:4444 mvn test
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
