# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: maven

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest
a--- 
name: maven
networks: 
  seleniumGrid: ~
true: 
  pull_request: 
    branches: 
      - master
  push: 
    branches: 
      - master
  services: 
    chrome: 
      container_name: Chrome-1
      depends_on: 
        - selenium-hub
      environment: 
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - NODE_MAX_INSTANCES=2
        - NODE_MAX_SESSIONS=2
      image: "selenium/node-chrome:3.141.59-zinc"
      networks: 
        - seleniumGrid
    chrome2: 
      container_name: Chrome-2
      depends_on: 
        - selenium-hub
      environment: 
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - NODE_MAX_INSTANCES=2
        - NODE_MAX_SESSIONS=2
      image: "selenium/node-chrome:3.141.59-zinc"
      networks: 
        - seleniumGrid
    selenium-hub: 
      container_name: selenium-hub
      image: "selenium/hub:3.141.59-zinc"
      networks: 
        - seleniumGrid
      ports: 
        - "4444:4444"

        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8

services:

    selenium-hub:
        image: selenium/hub:3.141.59-zinc
        container_name: selenium-hub
        networks:
            - seleniumGrid
        ports:
            - "4444:4444"

    chrome:
        image: selenium/node-chrome:3.141.59-zinc
        container_name: Chrome-1
        networks:
            - seleniumGrid
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=2
            - NODE_MAX_SESSIONS=2

    chrome2:
        image: selenium/node-chrome:3.141.59-zinc
        container_name: Chrome-2
        networks:
            - seleniumGrid
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=2
            - NODE_MAX_SESSIONS=2

networks:
    seleniumGrid:
